apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pyapp
  name: pyapp
  labels:
    app: pyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: python-apm
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      env: 
        - name: REDIS_HOST
          value: redis-service.redis.svc.cluster.local
        - name: REDIS_PORT
          value: 6379
---

apiVersion: v1
kind: Service
metadata:
  namespace: pyapp
  name: pyapp-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: pyapp